language: python
python:
  - "3.5"

before_install:
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-get -y install sqlite3=3.7.15.1-1~travis1

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python -m unittest discover tests

after_success:
  - codecov

notifications:
  webhooks: https://tny.site/travis/
  email: false
