language: python
cache:
  pip: true
  apt: true

python:
  - "3.5"

addons:
  apt:
    sources:
      - sourceline: ppa:travis-ci/sqlite3
    packages:
      - sqlite3=3.7.15.1-1~travis1

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run tests.py

after_success:
  - codecov

notifications:
  webhooks: https://tny.site/travis/
  email: false
